
compile: 
	g++ -std=c++0x -O3 -Wall -o test main.cpp ScenarioLoader.cpp Timer.cpp Entry.cpp

dev:
	g++ -g -ggdb -O0 -fno-omit-frame-pointer -Wall -DTEST_FOR_PATH_CONNECTIVITY -o test main.cpp ScenarioLoader.cpp Timer.cpp Entry.cpp

clean:
	rm test

